version: '2'
services:
  redis:
    image: redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - redis-net
  redis-cli:
    image: redis
    links:
      - redis
    command: ["redis-cli", "-h", "redis", "ping"]
    #command: ["redis-cli", "-h", "redis"]
    container_name: redis-cli
    #stdin_open: true
    #tty: true
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
    